### ISSUE TITLE
what if  a page code read itself in memory hack?

### ISSUE THREAD

**Issue by coolboy4me** [asamy/ksm#15]
1. in memory hack module, when a page code read itself ,  ept voilation will happen again and agian...
    when set a page read/write only, the code reading the page that the code is in will cause voilation (because of executing)
   when set a page execute only, the code reading the page that the code is in will cause voilation (because of reading)

**Comment by asamy** [comment]
You're right, but eventually it will get to read it and it'll be ok, but if you want to avoid that, then probably checking RIP in the EPT violation against the page hook CPA (after translation) will do.
