### ISSUE TITLE
Driver Signing Fails on cross compiled driver

### ISSUE THREAD

**Issue by rohaaan** [asamy/ksm#20]
cross compiled driver on linux fails driver signing. As a result unsigned driver needs to be loaded.

**Comment by rohaaan** [comment]
>> It works fine for me with
Are you cross compiling the binary on Linux for Windows?
I am cross compiling on Ubuntu Linux for Windows.

>>How are you signing it?
As above.

The problem I am facing is:
Digital Signature Tab doesnot appear in  the ksm.sys properties on windows.

**Comment by asamy** [comment]
No, I don't know if there is a way to sign it from Linux, what are you using?

**Comment by rohaaan** [comment]
I am signing on windows but compiling on Linux..

**Comment by asamy** [comment]
Hmm, that's weird...   What's the output of the command?

**Comment by rohaaan** [comment]
Driver signing works on latest recompile. Digital signature tab now present.
please close this issue.
